on:
  workflow_run:
    workflows: [main]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed ${{ github.event.workflow_run }}'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo 'The triggering workflow failed ${{ github.event.workflow_run }}'
      - name: test_our_action_step
        uses: ./ # Uses an action in the root directory
        id: failingRhymes
        with:
          openAIToken: ${{ secrets.OPENAI_API_TOKEN }}
          ghToken: ${{ secrets.GH_API_TOKEN }}
          failureDescription: "Commit ${{ github.ref }} by ${{ github.actor }}"
          user: '${{ github.event.workflow_run.actor.name }}'
      # Use the output from the `test_our_action_step` step
      - name: Get the output rhyme
        run: echo "The rhyme was ${{ steps.failingRhymes.outputs.rhyme }}"